# Generated by Django 3.2.8 on 2021-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.CharField(max_length=100)),
                ('Glucose', models.CharField(max_length=100)),
                ('Blood_Pressure', models.CharField(max_length=100)),
                ('Skin_Thickness', models.CharField(max_length=100)),
                ('Insulin', models.CharField(max_length=100)),
                ('BMI', models.CharField(max_length=100)),
                ('Diabetes_Pedigree_Function', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
