# Generated by Django 2.2.5 on 2021-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20211128_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatas',
            name='result_s',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
